// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/lesson.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentRequest) Reset() {
	*x = CreateContentRequest{}
	mi := &file_proto_lesson_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentRequest) ProtoMessage() {}

func (x *CreateContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentRequest.ProtoReflect.Descriptor instead.
func (*CreateContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_proto_rawDescGZIP(), []int{0}
}

func (x *CreateContentRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type CreateContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContentResponse) Reset() {
	*x = CreateContentResponse{}
	mi := &file_proto_lesson_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContentResponse) ProtoMessage() {}

func (x *CreateContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContentResponse.ProtoReflect.Descriptor instead.
func (*CreateContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_proto_rawDescGZIP(), []int{1}
}

func (x *CreateContentResponse) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type GetContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentRequest) Reset() {
	*x = GetContentRequest{}
	mi := &file_proto_lesson_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentRequest) ProtoMessage() {}

func (x *GetContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentRequest.ProtoReflect.Descriptor instead.
func (*GetContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_proto_rawDescGZIP(), []int{2}
}

func (x *GetContentRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type GetContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContentResponse) Reset() {
	*x = GetContentResponse{}
	mi := &file_proto_lesson_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContentResponse) ProtoMessage() {}

func (x *GetContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContentResponse.ProtoReflect.Descriptor instead.
func (*GetContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_proto_rawDescGZIP(), []int{3}
}

func (x *GetContentResponse) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type CreateLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentId     string                 `protobuf:"bytes,1,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLessonRequest) Reset() {
	*x = CreateLessonRequest{}
	mi := &file_proto_lesson_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLessonRequest) ProtoMessage() {}

func (x *CreateLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLessonRequest.ProtoReflect.Descriptor instead.
func (*CreateLessonRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_proto_rawDescGZIP(), []int{4}
}

func (x *CreateLessonRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type CreateLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootId        string                 `protobuf:"bytes,1,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	VersionNumber int32                  `protobuf:"varint,2,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLessonResponse) Reset() {
	*x = CreateLessonResponse{}
	mi := &file_proto_lesson_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLessonResponse) ProtoMessage() {}

func (x *CreateLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLessonResponse.ProtoReflect.Descriptor instead.
func (*CreateLessonResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_proto_rawDescGZIP(), []int{5}
}

func (x *CreateLessonResponse) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

func (x *CreateLessonResponse) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

type CreateVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootId        string                 `protobuf:"bytes,1,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	ContentId     string                 `protobuf:"bytes,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVersionRequest) Reset() {
	*x = CreateVersionRequest{}
	mi := &file_proto_lesson_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionRequest) ProtoMessage() {}

func (x *CreateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionRequest.ProtoReflect.Descriptor instead.
func (*CreateVersionRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_proto_rawDescGZIP(), []int{6}
}

func (x *CreateVersionRequest) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

func (x *CreateVersionRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type CreateVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootId        string                 `protobuf:"bytes,1,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	VersionNumber int32                  `protobuf:"varint,2,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVersionResponse) Reset() {
	*x = CreateVersionResponse{}
	mi := &file_proto_lesson_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionResponse) ProtoMessage() {}

func (x *CreateVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionResponse.ProtoReflect.Descriptor instead.
func (*CreateVersionResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_proto_rawDescGZIP(), []int{7}
}

func (x *CreateVersionResponse) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

func (x *CreateVersionResponse) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

type PublishVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootId        string                 `protobuf:"bytes,1,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	VersionNumber int32                  `protobuf:"varint,2,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishVersionRequest) Reset() {
	*x = PublishVersionRequest{}
	mi := &file_proto_lesson_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishVersionRequest) ProtoMessage() {}

func (x *PublishVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishVersionRequest.ProtoReflect.Descriptor instead.
func (*PublishVersionRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_proto_rawDescGZIP(), []int{8}
}

func (x *PublishVersionRequest) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

func (x *PublishVersionRequest) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

type PublishVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishVersionResponse) Reset() {
	*x = PublishVersionResponse{}
	mi := &file_proto_lesson_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishVersionResponse) ProtoMessage() {}

func (x *PublishVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishVersionResponse.ProtoReflect.Descriptor instead.
func (*PublishVersionResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_proto_rawDescGZIP(), []int{9}
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootId        string                 `protobuf:"bytes,1,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	VersionNumber int32                  `protobuf:"varint,2,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_proto_lesson_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_proto_rawDescGZIP(), []int{10}
}

func (x *GetVersionRequest) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

func (x *GetVersionRequest) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RootId        string                 `protobuf:"bytes,1,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	VersionNumber int32                  `protobuf:"varint,2,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	ContentId     string                 `protobuf:"bytes,3,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_proto_lesson_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_proto_rawDescGZIP(), []int{11}
}

func (x *GetVersionResponse) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

func (x *GetVersionResponse) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *GetVersionResponse) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

type DiffContentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromContentId string                 `protobuf:"bytes,1,opt,name=from_content_id,json=fromContentId,proto3" json:"from_content_id,omitempty"`
	ToContentId   string                 `protobuf:"bytes,2,opt,name=to_content_id,json=toContentId,proto3" json:"to_content_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffContentRequest) Reset() {
	*x = DiffContentRequest{}
	mi := &file_proto_lesson_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffContentRequest) ProtoMessage() {}

func (x *DiffContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffContentRequest.ProtoReflect.Descriptor instead.
func (*DiffContentRequest) Descriptor() ([]byte, []int) {
	return file_proto_lesson_proto_rawDescGZIP(), []int{12}
}

func (x *DiffContentRequest) GetFromContentId() string {
	if x != nil {
		return x.FromContentId
	}
	return ""
}

func (x *DiffContentRequest) GetToContentId() string {
	if x != nil {
		return x.ToContentId
	}
	return ""
}

type DiffContentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diff          string                 `protobuf:"bytes,1,opt,name=diff,proto3" json:"diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffContentResponse) Reset() {
	*x = DiffContentResponse{}
	mi := &file_proto_lesson_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffContentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffContentResponse) ProtoMessage() {}

func (x *DiffContentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lesson_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffContentResponse.ProtoReflect.Descriptor instead.
func (*DiffContentResponse) Descriptor() ([]byte, []int) {
	return file_proto_lesson_proto_rawDescGZIP(), []int{13}
}

func (x *DiffContentResponse) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

var File_proto_lesson_proto protoreflect.FileDescriptor

const file_proto_lesson_proto_rawDesc = "" +
	"\n" +
	"\x12proto/lesson.proto\x12\x06lesson\"*\n" +
	"\x14CreateContentRequest\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\"6\n" +
	"\x15CreateContentResponse\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\"2\n" +
	"\x11GetContentRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\"(\n" +
	"\x12GetContentResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\tR\x04body\"4\n" +
	"\x13CreateLessonRequest\x12\x1d\n" +
	"\n" +
	"content_id\x18\x01 \x01(\tR\tcontentId\"V\n" +
	"\x14CreateLessonResponse\x12\x17\n" +
	"\aroot_id\x18\x01 \x01(\tR\x06rootId\x12%\n" +
	"\x0eversion_number\x18\x02 \x01(\x05R\rversionNumber\"N\n" +
	"\x14CreateVersionRequest\x12\x17\n" +
	"\aroot_id\x18\x01 \x01(\tR\x06rootId\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\tR\tcontentId\"W\n" +
	"\x15CreateVersionResponse\x12\x17\n" +
	"\aroot_id\x18\x01 \x01(\tR\x06rootId\x12%\n" +
	"\x0eversion_number\x18\x02 \x01(\x05R\rversionNumber\"W\n" +
	"\x15PublishVersionRequest\x12\x17\n" +
	"\aroot_id\x18\x01 \x01(\tR\x06rootId\x12%\n" +
	"\x0eversion_number\x18\x02 \x01(\x05R\rversionNumber\"\x18\n" +
	"\x16PublishVersionResponse\"S\n" +
	"\x11GetVersionRequest\x12\x17\n" +
	"\aroot_id\x18\x01 \x01(\tR\x06rootId\x12%\n" +
	"\x0eversion_number\x18\x02 \x01(\x05R\rversionNumber\"s\n" +
	"\x12GetVersionResponse\x12\x17\n" +
	"\aroot_id\x18\x01 \x01(\tR\x06rootId\x12%\n" +
	"\x0eversion_number\x18\x02 \x01(\x05R\rversionNumber\x12\x1d\n" +
	"\n" +
	"content_id\x18\x03 \x01(\tR\tcontentId\"`\n" +
	"\x12DiffContentRequest\x12&\n" +
	"\x0ffrom_content_id\x18\x01 \x01(\tR\rfromContentId\x12\"\n" +
	"\rto_content_id\x18\x02 \x01(\tR\vtoContentId\")\n" +
	"\x13DiffContentResponse\x12\x12\n" +
	"\x04diff\x18\x01 \x01(\tR\x04diff2\xa3\x01\n" +
	"\x0eContentService\x12L\n" +
	"\rCreateContent\x12\x1c.lesson.CreateContentRequest\x1a\x1d.lesson.CreateContentResponse\x12C\n" +
	"\n" +
	"GetContent\x12\x19.lesson.GetContentRequest\x1a\x1a.lesson.GetContentResponse2\xc0\x02\n" +
	"\x0fMetadataService\x12I\n" +
	"\fCreateLesson\x12\x1b.lesson.CreateLessonRequest\x1a\x1c.lesson.CreateLessonResponse\x12L\n" +
	"\rCreateVersion\x12\x1c.lesson.CreateVersionRequest\x1a\x1d.lesson.CreateVersionResponse\x12O\n" +
	"\x0ePublishVersion\x12\x1d.lesson.PublishVersionRequest\x1a\x1e.lesson.PublishVersionResponse\x12C\n" +
	"\n" +
	"GetVersion\x12\x19.lesson.GetVersionRequest\x1a\x1a.lesson.GetVersionResponse2U\n" +
	"\vDiffService\x12F\n" +
	"\vDiffContent\x12\x1a.lesson.DiffContentRequest\x1a\x1b.lesson.DiffContentResponseB.Z,github.com/kenny/lessons/demo/internal/pb;pbb\x06proto3"

var (
	file_proto_lesson_proto_rawDescOnce sync.Once
	file_proto_lesson_proto_rawDescData []byte
)

func file_proto_lesson_proto_rawDescGZIP() []byte {
	file_proto_lesson_proto_rawDescOnce.Do(func() {
		file_proto_lesson_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lesson_proto_rawDesc), len(file_proto_lesson_proto_rawDesc)))
	})
	return file_proto_lesson_proto_rawDescData
}

var file_proto_lesson_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_lesson_proto_goTypes = []any{
	(*CreateContentRequest)(nil),   // 0: lesson.CreateContentRequest
	(*CreateContentResponse)(nil),  // 1: lesson.CreateContentResponse
	(*GetContentRequest)(nil),      // 2: lesson.GetContentRequest
	(*GetContentResponse)(nil),     // 3: lesson.GetContentResponse
	(*CreateLessonRequest)(nil),    // 4: lesson.CreateLessonRequest
	(*CreateLessonResponse)(nil),   // 5: lesson.CreateLessonResponse
	(*CreateVersionRequest)(nil),   // 6: lesson.CreateVersionRequest
	(*CreateVersionResponse)(nil),  // 7: lesson.CreateVersionResponse
	(*PublishVersionRequest)(nil),  // 8: lesson.PublishVersionRequest
	(*PublishVersionResponse)(nil), // 9: lesson.PublishVersionResponse
	(*GetVersionRequest)(nil),      // 10: lesson.GetVersionRequest
	(*GetVersionResponse)(nil),     // 11: lesson.GetVersionResponse
	(*DiffContentRequest)(nil),     // 12: lesson.DiffContentRequest
	(*DiffContentResponse)(nil),    // 13: lesson.DiffContentResponse
}
var file_proto_lesson_proto_depIdxs = []int32{
	0,  // 0: lesson.ContentService.CreateContent:input_type -> lesson.CreateContentRequest
	2,  // 1: lesson.ContentService.GetContent:input_type -> lesson.GetContentRequest
	4,  // 2: lesson.MetadataService.CreateLesson:input_type -> lesson.CreateLessonRequest
	6,  // 3: lesson.MetadataService.CreateVersion:input_type -> lesson.CreateVersionRequest
	8,  // 4: lesson.MetadataService.PublishVersion:input_type -> lesson.PublishVersionRequest
	10, // 5: lesson.MetadataService.GetVersion:input_type -> lesson.GetVersionRequest
	12, // 6: lesson.DiffService.DiffContent:input_type -> lesson.DiffContentRequest
	1,  // 7: lesson.ContentService.CreateContent:output_type -> lesson.CreateContentResponse
	3,  // 8: lesson.ContentService.GetContent:output_type -> lesson.GetContentResponse
	5,  // 9: lesson.MetadataService.CreateLesson:output_type -> lesson.CreateLessonResponse
	7,  // 10: lesson.MetadataService.CreateVersion:output_type -> lesson.CreateVersionResponse
	9,  // 11: lesson.MetadataService.PublishVersion:output_type -> lesson.PublishVersionResponse
	11, // 12: lesson.MetadataService.GetVersion:output_type -> lesson.GetVersionResponse
	13, // 13: lesson.DiffService.DiffContent:output_type -> lesson.DiffContentResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_lesson_proto_init() }
func file_proto_lesson_proto_init() {
	if File_proto_lesson_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lesson_proto_rawDesc), len(file_proto_lesson_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_lesson_proto_goTypes,
		DependencyIndexes: file_proto_lesson_proto_depIdxs,
		MessageInfos:      file_proto_lesson_proto_msgTypes,
	}.Build()
	File_proto_lesson_proto = out.File
	file_proto_lesson_proto_goTypes = nil
	file_proto_lesson_proto_depIdxs = nil
}
